name: Build and deploy container to App Service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://javaimageregistry.azurecr.io/
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: javaimageregistry.azurecr.io/petclinic-app:${{ github.sha }}
          file: ./Dockerfile

  deploy-to-multitenant:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: multi-tenant
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Login with Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to multi-tenant Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: javademo-mtapp
          images: javaimageregistry.azurecr.io/petclinic-app:${{ github.sha }}
          
  deploy-to-ase:
    runs-on: ubuntu-latest
    needs: build
        
    steps:
      - name: Login with Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Deploy to App Service Environment
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config set --resource-group Isolated-Java-app-rg \
              --name javademo-aseapp \
              --linux-fx-version 'DOCKER|javaimageregistry.azurecr.io/petclinic-app:${{ github.sha }}'
